project_name: vin

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/vin/main.go
    binary: vin
    ldflags:
      - -s -w
      - -X github.com/skmatz/vin/cmd/vin/cmd.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - 386
      - amd64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      386: i386
      amd64: x86_64

release:
  prerelease: auto
